on: workflow_dispatch
jobs:
  osx_mdp_tests:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
        architecture: 'x64'

    - name: Install package and dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -e .

    - name: Run tests
      run: pytest
#  ubuntu_mdp_tests:
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/checkout@v2
#    - name: Set up Python 3.7
#      uses: actions/setup-python@v2
#      with:
#        python-version: '3.7'
#        architecture: 'x64'
#    - name: Install dependencies
#      run: |
#        python -m pip install --upgrade pip
#        pip install coverage
#    - name: Setup # needs -e flag for coverage tests to work
#      run: pip install -e .
#    - name: Run tests and generate coverage report
#      run: |
#        pytest
#    - name: Upload coverage to Codecov
#      uses: codecov/codecov-action@v1
#      with:
#        name: codecov-report
#        fail_ci_if_error: false
